version: "3"

services:
  mysql:
    image: mysql:5.6
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'online_store'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
